# Generated by Django 4.1.5 on 2023-01-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_category_options_alter_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='categories',
        ),
    ]
